// flow-typed signature: e07bba1261388616fb2e48a1f5cfb7ae
// flow-typed version: <<STUB>>/webcola_v^3.4.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webcola'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webcola' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webcola/dist/index' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/adaptor' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/batch' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/d3adaptor' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/d3v3adaptor' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/d3v4adaptor' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/descent' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/geom' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/gridrouter' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/handledisconnected' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/layout' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/layout3d' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/linklengths' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/powergraph' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/pqueue' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/project2D' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/rbtree' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/rectangle' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/shortestpaths' {
  declare module.exports: any;
}

declare module 'webcola/dist/src/vpsc' {
  declare module.exports: any;
}

declare module 'webcola/Gruntfile' {
  declare module.exports: any;
}

declare module 'webcola/tasks/examples' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/cola' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/cola.min' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/index' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/adaptor' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/batch' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/d3adaptor' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/d3v3adaptor' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/d3v4adaptor' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/descent' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/geom' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/gridrouter' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/handledisconnected' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/layout' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/layout3d' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/linklengths' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/powergraph' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/pqueue' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/rbtree' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/rectangle' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/shortestpaths' {
  declare module.exports: any;
}

declare module 'webcola/WebCola/src/vpsc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webcola/dist/index.js' {
  declare module.exports: $Exports<'webcola/dist/index'>;
}
declare module 'webcola/dist/src/adaptor.js' {
  declare module.exports: $Exports<'webcola/dist/src/adaptor'>;
}
declare module 'webcola/dist/src/batch.js' {
  declare module.exports: $Exports<'webcola/dist/src/batch'>;
}
declare module 'webcola/dist/src/d3adaptor.js' {
  declare module.exports: $Exports<'webcola/dist/src/d3adaptor'>;
}
declare module 'webcola/dist/src/d3v3adaptor.js' {
  declare module.exports: $Exports<'webcola/dist/src/d3v3adaptor'>;
}
declare module 'webcola/dist/src/d3v4adaptor.js' {
  declare module.exports: $Exports<'webcola/dist/src/d3v4adaptor'>;
}
declare module 'webcola/dist/src/descent.js' {
  declare module.exports: $Exports<'webcola/dist/src/descent'>;
}
declare module 'webcola/dist/src/geom.js' {
  declare module.exports: $Exports<'webcola/dist/src/geom'>;
}
declare module 'webcola/dist/src/gridrouter.js' {
  declare module.exports: $Exports<'webcola/dist/src/gridrouter'>;
}
declare module 'webcola/dist/src/handledisconnected.js' {
  declare module.exports: $Exports<'webcola/dist/src/handledisconnected'>;
}
declare module 'webcola/dist/src/layout.js' {
  declare module.exports: $Exports<'webcola/dist/src/layout'>;
}
declare module 'webcola/dist/src/layout3d.js' {
  declare module.exports: $Exports<'webcola/dist/src/layout3d'>;
}
declare module 'webcola/dist/src/linklengths.js' {
  declare module.exports: $Exports<'webcola/dist/src/linklengths'>;
}
declare module 'webcola/dist/src/powergraph.js' {
  declare module.exports: $Exports<'webcola/dist/src/powergraph'>;
}
declare module 'webcola/dist/src/pqueue.js' {
  declare module.exports: $Exports<'webcola/dist/src/pqueue'>;
}
declare module 'webcola/dist/src/project2D.js' {
  declare module.exports: $Exports<'webcola/dist/src/project2D'>;
}
declare module 'webcola/dist/src/rbtree.js' {
  declare module.exports: $Exports<'webcola/dist/src/rbtree'>;
}
declare module 'webcola/dist/src/rectangle.js' {
  declare module.exports: $Exports<'webcola/dist/src/rectangle'>;
}
declare module 'webcola/dist/src/shortestpaths.js' {
  declare module.exports: $Exports<'webcola/dist/src/shortestpaths'>;
}
declare module 'webcola/dist/src/vpsc.js' {
  declare module.exports: $Exports<'webcola/dist/src/vpsc'>;
}
declare module 'webcola/Gruntfile.js' {
  declare module.exports: $Exports<'webcola/Gruntfile'>;
}
declare module 'webcola/tasks/examples.js' {
  declare module.exports: $Exports<'webcola/tasks/examples'>;
}
declare module 'webcola/WebCola/cola.js' {
  declare module.exports: $Exports<'webcola/WebCola/cola'>;
}
declare module 'webcola/WebCola/cola.min.js' {
  declare module.exports: $Exports<'webcola/WebCola/cola.min'>;
}
declare module 'webcola/WebCola/index.js' {
  declare module.exports: $Exports<'webcola/WebCola/index'>;
}
declare module 'webcola/WebCola/src/adaptor.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/adaptor'>;
}
declare module 'webcola/WebCola/src/batch.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/batch'>;
}
declare module 'webcola/WebCola/src/d3adaptor.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/d3adaptor'>;
}
declare module 'webcola/WebCola/src/d3v3adaptor.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/d3v3adaptor'>;
}
declare module 'webcola/WebCola/src/d3v4adaptor.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/d3v4adaptor'>;
}
declare module 'webcola/WebCola/src/descent.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/descent'>;
}
declare module 'webcola/WebCola/src/geom.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/geom'>;
}
declare module 'webcola/WebCola/src/gridrouter.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/gridrouter'>;
}
declare module 'webcola/WebCola/src/handledisconnected.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/handledisconnected'>;
}
declare module 'webcola/WebCola/src/layout.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/layout'>;
}
declare module 'webcola/WebCola/src/layout3d.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/layout3d'>;
}
declare module 'webcola/WebCola/src/linklengths.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/linklengths'>;
}
declare module 'webcola/WebCola/src/powergraph.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/powergraph'>;
}
declare module 'webcola/WebCola/src/pqueue.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/pqueue'>;
}
declare module 'webcola/WebCola/src/rbtree.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/rbtree'>;
}
declare module 'webcola/WebCola/src/rectangle.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/rectangle'>;
}
declare module 'webcola/WebCola/src/shortestpaths.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/shortestpaths'>;
}
declare module 'webcola/WebCola/src/vpsc.js' {
  declare module.exports: $Exports<'webcola/WebCola/src/vpsc'>;
}
