/* eslint-disable import/prefer-default-export */
export const StyleLib: any = {
	style: {
		background: 'background',
		'background-attachment': 'backgroundAttachment',
		'background-color': 'backgroundColor',
		'background-image': 'backgroundImage',
		'background-position': 'backgroundPosition',
		'background-size': 'backgroundSize',
		'background-position-x': 'backgroundPositionX',
		'background-position-y': 'backgroundPositionY',
		'background-repeat': 'backgroundRepeat',
		border: 'border',
		'border-bottom': 'borderBottom',
		'border-bottom-color': 'borderBottomColor',
		'border-bottom-style': 'borderBottomStyle',
		'border-bottom-width': 'borderBottomWidth',
		'border-color': 'borderColor',
		'border-left': 'borderLeft',
		'border-left-color': 'borderLeftColor',
		'border-left-style': 'borderLeftStyle',
		'border-left-width': 'borderLeftWidth',
		'border-right': 'borderRight',
		'border-radius': 'borderRadius',
		cursor: 'pointer',
		'border-right-color': 'borderRightColor',
		'border-right-style': 'borderRightStyle',
		'border-right-wstyles.jidth': 'borderRightWidth',
		'border-style': 'borderStyle',
		'border-top': 'borderTop',
		'border-top-color': 'borderTopColor',
		'border-top-style': 'borderTopStyle',
		'border-top-width': 'borderTopWidth',
		'border-width': 'borderWidth',
		clear: 'clear',
		clip: 'clip',
		color: 'color',
		display: 'display',
		filter: 'filter',
		flex: 'flex',
		'flex-direction': 'flexDirection',
		'flex-flow': 'flexFlow',
		'justify-content': 'justifyContent',
		'align-items': 'alignItems',
		'align-content': 'alignContents',
		float: 'cssFloat',
		font: 'font',
		'font-family': 'fontFamily',
		'font-size': 'fontSize',
		'font-variant': 'fontVariant',
		'font-weight': 'fontWeight',
		height: 'height',
		left: 'left',
		'grid-template-columns': 'gridTemplateColumns',
		'grid-template-rows': 'gridTemplateRows',
		'grid-template-areas': 'gridTemplateAreas',
		'grid-template': 'gridTemplate',
		'grid-column-gap': 'gridColumnGap',
		'grid-row-gap': 'gridRowGap',
		'grid-gap': 'gridGap',
		'justify-items': 'justifyItems',
		'place-items': 'placeItems',
		'place-content': 'placeContent',
		'grid-auto-columns': 'gridAutoColumns',
		'grid-auto-rows': 'gridAutoRows',
		'grid-auto-flow': 'gridAutoFlow',
		grid: 'grid',
		'grid-column-start': 'gridColumnStart',
		'grid-column-end': 'gridColumnEnd',
		'grid-row-start': 'gridRowStart',
		'grid-row-end': 'gridRowEnd',
		'grid-column': 'gridColumn',
		'grid-row': 'gridRow',
		'grid-area': 'gridArea',
		'justify-self': 'justifySelf',
		'align-self': 'alignSelf',
		'place-self': 'placeSelf',
		'letter-spacing': 'letterSpacing',
		'line-height': 'lineHeight',
		'list-style': 'listStyle',
		'list-style-image': 'listStyleImage',
		'list-style-position': 'listStylePosition',
		'list-style-type': 'listStyleType',
		margin: 'margin',
		'margin-bottom': 'marginBottom',
		opacity: 'opacity',
		'margin-left': 'marginLeft',
		'margin-right': 'marginRight',
		'margin-top': 'marginTop',
		overflow: 'overflow',
		padding: 'padding',
		'padding-bottom': 'paddingBottom',
		'box-shadow': 'boxShadow',
		'padding-left': 'paddingLeft',
		'padding-right': 'paddingRight',
		'padding-top': 'paddingTop',
		'page-break-after': 'pageBreakAfter',
		'page-break-before': 'pageBreakBefore',
		position: 'position',
		'stroke-dasharray': 'strokeDasharray',
		'stroke-dashoffset': 'strokeDashoffset',
		'stroke-width': 'strokeWidth',
		'text-align': 'textAlign',
		'text-decoration': 'textDecoration',
		'text-indent': 'textIndent',
		'text-transform': 'textTransform',
		'min-width': 'minWidth',
		'max-width': 'maxWidth',
		'min-height': 'minHeight',
		'max-height': 'maxHeight',
		top: 'top',
		'vertical-align': 'verticalAlign',
		visibility: 'visibility',
		width: 'width',
		transition: 'transition',
		'z-index': 'zIndex'
	},
	js: {},
	css: {}
};
(function () {
	Object.keys(StyleLib.style).forEach((v) => {
		StyleLib.js[StyleLib.style[v]] = v;
		let type = null;
		if (v.toLowerCase().indexOf('color') !== -1) {
			type = 'color';
		}
		StyleLib.css[StyleLib.style[v]] = {
			placeholder: v,
			label: v,
			key: v,
			type
		};
	});
})();
